Ac 29672 terraform add collection id to policy app
Broadcom/terraform-provider-luminate pull request #44
Opened 2023-06-22 06:47 UTC by yuvalstyrbrod

1. add ability to create policy or app with collection id 
2. assign roles: site, collection and tenant

2023-07-03 14:46 UTC, yiftahHaim commented
please remove all policy entity assigner code

2023-07-04 18:04 UTC, gitomics requested changes

2023-07-04 18:04 UTC, gitomics commented on service/role_bindings.go
> +// CreateCollectionRoleBindings assign tenant role to admin
assign tenant role to admin
->
assign collection role to admin

2023-07-04 18:04 UTC, gitomics commented on service/role_bindings.go
> +// CreateSiteRoleBindings assign tenant role to admin
assign site role to admin

2023-07-04 18:04 UTC, gitomics commented on service/role_bindings.go
> +// ReadRoleBindings get tenant role
get tenant role
 ->
  get role

2023-07-05 06:59 UTC, yuvalstyrbrod commented on service/dto/dto.go
> -	ManagedDeviceOpswatGroupsArgument      = "OPSWAT_GROUPS"
not related to rbac, but, needed to pass all AT due to a change in policy-service

2023-07-05 13:23 UTC, yuvalstyrbrod commented on service/dto/access_policy_converter.go
> -			argumentsMap[ManagedDeviceOpswatGroupsArgument] = []string{}
not related to rbac, but, needed to pass all AT due to a change in policy-service

2023-07-06 07:02 UTC, yiftahHaim approved these changes
looks good to me.

2023-07-06 09:54 UTC, gitomics approved these changes

2023-07-06 12:32 UTC, merged