Ac 32436 terraform upgrade version
Broadcom/terraform-provider-luminate pull request #59
Opened 2023-08-23 12:44 UTC by yuvalstyrbrod

-  new terraform version 
-  remove vendor
-  fix arm link

2023-08-23 13:35 UTC, gitomics requested changes

2023-08-23 13:35 UTC, gitomics commented on provider/resource_access_policy.go
> +									Description:  "Indicate whatever to restrict access to Opswat MetaAccess",
whatever -> whether

2023-08-23 13:35 UTC, gitomics commented on provider/resource_access_policy.go
> +									Description:  "Indicate whatever to restrict access to Opswat MetaAccess",
Indicate whatever to restrict access to Opswat MetaAccess

Indicate whether to restrict access according to Opswat MetaAccess

2023-08-23 13:35 UTC, gitomics commented on provider/resource_tcp_application.go
> -	d.Set("internal_address", TCPApplicationInternalAddress)
safe to remove?

2023-08-23 13:35 UTC, gitomics commented on provider/resource_web_access_policy.go
> -	conditionsResource := webSchema["conditions"].Elem.(*schema.Resource)
safe to remove?

2023-08-23 13:35 UTC, gitomics commented on service/dto/access_policy_converter.go
> -		if accessPolicy.Conditions.ManagedDevice.SymantecCloudSoc || accessPolicy.Conditions.ManagedDevice.SymantecWebSecurityService {
safe to remove?

2023-08-24 13:16 UTC, yuvalstyrbrod commented on provider/resource_web_access_policy.go
> -	conditionsResource := webSchema["conditions"].Elem.(*schema.Resource)
we have conditions as part of the baseAccessPolicyBaseSchema

2023-08-24 13:18 UTC, yuvalstyrbrod commented on service/dto/access_policy_converter.go
> -		if accessPolicy.Conditions.ManagedDevice.SymantecCloudSoc || accessPolicy.Conditions.ManagedDevice.SymantecWebSecurityService {
i'm not removing it getting it from a function getDeviceArguments()

2023-08-24 13:24 UTC, yuvalstyrbrod commented on provider/resource_tcp_application.go
> -	d.Set("internal_address", TCPApplicationInternalAddress)
we are putting a dummy value "tcp://luminate-dummy:22" ,
don't want it to be part of the user state

2023-08-25 08:14 UTC, gitomics approved these changes

2023-08-27 06:58 UTC, merged