AC-32928| impl dns group and dns server resiliency coed. tests
Broadcom/terraform-provider-luminate pull request #78
Opened 2024-11-14 16:39 UTC by yiftahhaimbroad

implementation of DNS Server resiliency & DNS group resiliency ,  tests

2024-11-14 16:46 UTC, gitomics commented on README.md
> +Provides crud of dns resiliency servers
crud -> CRUD

2024-11-14 17:21 UTC, gitomics requested changes

2024-11-14 17:21 UTC, gitomics commented on provider/resource_dns_server_resiliency.go
> +		Description:  "DNS server name",
fix description

2024-11-14 17:21 UTC, gitomics commented on provider/resource_dns_server_resiliency.go
> +	DNSGroup, err := client.DNSResiliencyAPI.GetDNSGroup(DNSGroupID)
do we have to get the dns group before calling create?
our BE should be returning an error if there is no such group while we are creating the server, so seems redudndant here in the provider

2024-11-14 17:21 UTC, gitomics commented on provider/resource_dns_group_resiliency.go
> +	d.SetId(DNSGroup.ID)
how does it make sense we only set the id here?
shouldnt we be copying all the data from BE into the  d *schema.ResourceData

2024-11-14 17:21 UTC, gitomics commented on provider/resource_dns_server_resiliency.go
> +	d.SetId(DNSResiliencyServerID)
how does it make sense we only set the id here?
shouldnt we be copying all the data from BE into the  d *schema.ResourceData

2024-11-14 17:21 UTC, gitomics commented on provider/resource_dns_server_resiliency.go
> +	_, err := client.DNSResiliencyAPI.GetDNServer(DNSResiliencyServerID, DNSResiliencyGroupID)
odd that data from BE is not needed in read request..

2024-11-14 17:21 UTC, gitomics commented on provider/resource_dns_server_resiliency.go
> +	d.SetId(d.Id())
is SetId needed in each end of operation? shouldnt it be enough in create/delete event?

2024-11-14 17:21 UTC, gitomics commented on service/dns_resiliency.go
> +func (d *DNSResiliencyAPI) ListDNSGroups(input *sdk.DNSResiliencyApiListDnsGroupsOpts) (*sdk.DnsGroupOutputPage, error) {
unused, consider removing

2024-11-14 17:21 UTC, gitomics commented on service/dns_resiliency.go
> +	return &res, nil
not convertign with ConvertDnsGroupOutputTODTO

2024-11-14 17:21 UTC, gitomics commented on provider/resource_dns_server_resiliency_test.go
> +	domain_suffixes = ["%s"]
odd using %s only for domain suffixes, doesnt look like formatting is really needed here its just aconst string thats being inserted

2024-11-14 17:21 UTC, gitomics commented on provider/resource_dns_server_resiliency_test.go
> +				ExpectError: regexp.MustCompile(".*"),
expect any error? sounds odd

if its related to the cant delete last server then maybe we should be expecting just that error

2024-11-14 17:21 UTC, gitomics commented on provider/resource_dns_server_resiliency_test.go
> +func TestAccLuminateDNSServerResiliency(t *testing.T) {
consider adding a test were only the 2nd server is deleted and not expecting an error

2024-11-17 08:43 UTC, yiftahhaimbroad commented on README.md
> +Provides crud of dns resiliency servers
done

2024-11-17 08:43 UTC, yiftahhaimbroad commented on provider/resource_dns_group_resiliency.go
> +		DomainSuffixes:   d.Get("domain_suffixes").([]interface{}),
tried..

2024-11-17 08:43 UTC, yiftahhaimbroad commented on provider/resource_dns_group_resiliency.go
> +	disableDTO := &dto.EnableDisableDNSGroupDTO{
removed

2024-11-17 08:43 UTC, yiftahhaimbroad commented on service/dto/dto.go
> +	DomainSuffixes   []interface{} `json:"domainSuffixes"`
tried

2024-11-17 08:43 UTC, yiftahhaimbroad commented on provider/resource_dns_server_resiliency.go
> +		Description:  "DNS server name",
fixed

2024-11-17 08:45 UTC, yiftahhaimbroad commented on service/dns_resiliency.go
> +func (d *DNSResiliencyAPI) ListDNSGroups(input *sdk.DNSResiliencyApiListDnsGroupsOpts) (*sdk.DnsGroupOutputPage, error) {
removed

2024-11-17 08:46 UTC, yiftahhaimbroad commented on provider/resource_dns_server_resiliency_test.go
> +	domain_suffixes = ["%s"]
agree

2024-11-17 08:46 UTC, yiftahhaimbroad commented on provider/resource_dns_server_resiliency_test.go
> +				ExpectError: regexp.MustCompile(".*"),
working on fix

2024-12-16 12:27 UTC, yuvalstyrbrod approved these changes

2024-12-16 12:43 UTC, gitomics approved these changes

2024-12-18 07:43 UTC, merged